INSERT INTO foundtier(nameF, tierF) VALUES('alameda research', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('multicoin capital', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('fundamental labs', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('andreessen horowitz (a16z)', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('sequoia capital', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('circle', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('pantera capital', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('kenetic capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('polychain capital', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('arrington xrp capital', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('three arrows capital', 4);
INSERT INTO foundtier(nameF, tierF) VALUES('digital currency group', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('coinfund', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('spartan group', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('cms holdings', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('coinbase ventures', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('hashkey capital', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('blockchain capital', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('defiance capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('dragonfly capital', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('exnetwork capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('ngc ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('binance labs', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('fifth era', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('sino global capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('ribbit capital', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('coin98 ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('au21 capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('republic', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('fabric ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('hashed fund', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('boost vc', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('delphi digital', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('rockaway blockchain fund', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('galaxy digital', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('tiger global management', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('signum capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('paradigm', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('shima capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('onblock ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('1confirmation', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('animoca brands', 1);
INSERT INTO foundtier(nameF, tierF) VALUES('br capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('placeholder ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('bitscale capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('youbi capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('fenbushi capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('zmt capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('slow ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('union square ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('mapleblock capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('hyperchain capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('zbs capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('snz holding', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('zee prime capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('softbank', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('waterdrip capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('variant', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('krypital group', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('ybb foundation', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('illusionist group', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('sv angel', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('standard crypto', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('moonwhale ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('framework ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('lemniscap', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('electric capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('parafi capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('dhvc', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('chain capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('galaxy interactive', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('continue capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('ftx ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('fbg capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('jump capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('muhabbit capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('outlier ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('ghaf capital partners', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('makers fund', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('mechanism capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('lightspeed venture partners', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('eden block', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('amber group', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('6th man ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('tribe capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('divergence ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('scalar capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('one block capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('folius ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('blockchange ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('ideo colab ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('ledgerprime', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('iosg', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('spark digital capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('robot ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('a_capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('greylock partners', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('draper dragon', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('ellipti', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('hack vc', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('huobi capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('samsungnext', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('dapper labs', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('crypto.com capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('uniswap labs ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('rr2 capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('maven 11 capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('csp dao', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('gumi cryptos', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('op crypto', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('dfg capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('kernel ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('backed', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('lattice', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('panda capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('mentha partners', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('the lao', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('gbv capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('kingsway capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('a195 capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('ld capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('1kx', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('polygon studios', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('okx blockdream ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('jump crypto', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('fairum ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('blocktower capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('genblock capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('morningstar ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('digital strategies', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('solana ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('free company', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('sfermion', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('woodstock fund', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('defi alliance', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('master ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('longhash ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('metacartel ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('jane street capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('titans ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('nascent', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('sevenx ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('blockchain.com', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('advanced blockchain', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('qcp capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('vendetta capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('petrock capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('magnus capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('arkstream capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('lotus capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('solar eco fund', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('bixin ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('hypersphere ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('double peak', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('wintermute', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('yield guild games', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('kyros ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('ethereal ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('7 o clock capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('distributed global', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('extra watts', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('figment capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('infinity capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('consensys mesh', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('bitkraft ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('basics capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('trustdao capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('dialectic capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('taureon capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('raptor capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('moonrock capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('rarestone capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('x21 digital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('mirana ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('dutch crypto investors', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('formless capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('skynet trading', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('ascensive assets', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('cmt digital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('trgc', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('rok capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('infinity ventures crypto', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('gsr', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('m6 venture', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('solidity ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('axia8 ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('dweb3 capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('dao maker', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('blackedge capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('black dragon capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('true ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('angeldao', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('d1 ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('3commas', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('ava labs', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('altonomy', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('paka', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('metrix.capital', 4);
INSERT INTO foundtier(nameF, tierF) VALUES('skyvision capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('blocksync ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('global coin research', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('kucoin labs', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('polygon fund', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('parachain ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('borderless capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('sky9 capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('merit circle', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('kyber network', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('tk ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('chromia', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('c2 ventures', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('matrixport', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('lancer capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('kosmos ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('cryptoj', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('maven capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('zokyo', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('hg ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('reblock', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('poolz ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('play ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('the chernin group', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('icetea labs', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('minted lab', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('avstar capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('valhalla capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('orangedao', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('ignite', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('egirl capital', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('0xventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('good games labs', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('oddiyana ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('tenzor capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('oracles investment group', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('twin apex capital', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('goldentree asset management', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('pluto digital assets', 2);
INSERT INTO foundtier(nameF, tierF) VALUES('alumni ventures group', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('big brain holdings', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('wings ventures', 3);
INSERT INTO foundtier(nameF, tierF) VALUES('gd10 ventures', 3);